### ISSUE TITLE
Build instructions seem outdated.

### ISSUE THREAD

**Issue by magnetophon** [bill-auger/loopidity#32]
When I did `make release` I got `make: *** No rule to make target 'release'.  Stop.`.

**Comment by magnetophon** [comment]
This was with the `linux` branch.
The master branch has issue #34

**Comment by bill-auger** [comment]
yes i consolidated the debug and release targets recently - if you want a debug build set CONFIG=debug - like:
```
CONFIG=debug make -j2
```
or in the root dir there is a script ./mk that i use during development - that builds and launches the local binary without installing

the README is still correct for the master branch IIRC - i usually update that last before merging dev branches into master - i will leave this issue open as a reminder

**Comment by magnetophon** [comment]
As discussed on IRC, I can build now, but not with `make release`, as suggested in the readme.
