### ISSUE TITLE
feature request: undo record

### ISSUE THREAD

**Issue by magnetophon** [bill-auger/loopidity#39]
When I make a mistake, I want to get rid of the last recording.

**Comment by bill-auger** [comment]
it has undo - that is primary trigger #2 - it is currently the ESC key

the real feature request here should be for documentation or at least an in-app 'help' panel

for now look at  and [Loopidity::HandleKeyEvent()](https://github.com/bill-auger/loopidity/blob/linux/src/loopidity.cpp#L353) and [Loopidity::HandleMouseEvent()](https://github.com/bill-auger/loopidity/blob/linux/src/loopidity.cpp#L375) to see what the buttons do
