### ISSUE TITLE
Please add documentation

### ISSUE THREAD

**Issue by magnetophon** [bill-auger/loopidity#40]
At the very least, you should add an explanation of space and KP0 to the readme.
Of course explanation on any other keys is needed too.

**Comment by bill-auger** [comment]
indeed - an in-app 'help' panel like freewheeling would be nice as well

for now look at  and [Loopidity::HandleKeyEvent()](https://github.com/bill-auger/loopidity/blob/linux/src/loopidity.cpp#L353) and [Loopidity::HandleMouseEvent()](https://github.com/bill-auger/loopidity/blob/linux/src/loopidity.cpp#L375) to see what the buttons do

**Comment by magnetophon** [comment]
Sure, in app help and a video would be nice, but a quick write-up in the readme can be done in 15 minutes, and would provide 90% of the usefulness.
I looked at those, and have trouble figuring out what some of them mean.

**Comment by bill-auger** [comment]
i started a wiki page for them - knock yerself out :) - that can be the beginning of the documentation - the problem for me is that they're are all crystal clear to me as is so i dont know which are the confusing ones

https://github.com/bill-auger/loopidity/wiki/Default-Controls-Cheat-Sheet

**Comment by magnetophon** [comment]
I did a bit of fromating, and added ?? where things are unclear.

**Comment by bill-auger** [comment]
thanks great job - i formatted it into a table and filled in the ???s

**Comment by magnetophon** [comment]
Great! We're getting somewhere!
TBH, I hadn't even noticed yet there was a main wiki page.

**Comment by bill-auger** [comment]
there wasnt

**Comment by bill-auger** [comment]
ive added a fairly complete walk-through tutorial to the wiki - that should be a good start

https://github.com/bill-auger/loopidity/wiki/Getting-Started
